"""
Django settings for genetica project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from datetime import timedelta

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = """
-----BEGIN RSA PRIVATE KEY-----
MIICWwIBAAKBgFbKy/72cEpDDXOvkQIIMii53b/71zo0Ct03O4QaSht4PpoFobF0
3lShkY3/zGWtRPxwvVB/FDv8tAlQ0KuMDJvX3S7N3Xbnv9sMfUDyBf23/9A7o9JC
4aKzWWBE+CVTktaswnkVRFWn+DAihSqs7Cl3pQzYMb82qRVJDAehCeppAgMBAAEC
gYA4xAsIh0aKS7DQqVO+cH3eBTL0DlOGzeMNLMLQdCFkNhE7y9Mlrbp8v+/jYBrf
paQpN9OagoNJeM6ICUNx7/eOcdKjB17tbUjaiDVLC9SBdC8atIwFhREo+I9C+PSq
Zg5O/qLy/at7oN9f2fZ1KxIgmnI9ziii5faKYmwBzAcYwQJBAKmlXLQyxA61pSja
NkDLjj/0Rq+06tcsPGJWx96bGNzNTDsYBZWHFZ1zhragFMBdQDcowNlmdfgkZgBf
oqC2lZ8CQQCC+LkyBbyeCwYalXP9lPHzBmJAHZJeGXXuDvLwlyDA996mHZbBln5d
3+pYXQQkISQKYfgXyrTZ1tzPwRr9ybL3AkBMuDHSdFrh5BfK/9QlPWkZVxlYgNLr
eF/egSxmaXG2+UkOOHDeDHcj+4jiskZwMDvINi/woTuceql+ZcGgOLI1AkAR2ZxD
+Qwv7giy7tOUKAyhtqkFXAJq2MV94IOzzqUkJ6Qst7OoRr6KRM5HpMW/ttSWpauO
co4bcnE9z2/CTw8ZAkEAml268J8MB0ytUddx9QoSiRhO18DixuOYvTx4PMHP8bQ/
bder0bdRkl8wvgp+uuGTBg+eSqJPf7JRtUmcdKY/wA==
-----END RSA PRIVATE KEY-----
"""

VERIFY_KEY = """
-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgFbKy/72cEpDDXOvkQIIMii53b/7
1zo0Ct03O4QaSht4PpoFobF03lShkY3/zGWtRPxwvVB/FDv8tAlQ0KuMDJvX3S7N
3Xbnv9sMfUDyBf23/9A7o9JC4aKzWWBE+CVTktaswnkVRFWn+DAihSqs7Cl3pQzY
Mb82qRVJDAehCeppAgMBAAE=
-----END PUBLIC KEY-----
"""
# SECURITY WARNING: don't run with debug turned on in production!
try:
    from .local_settings import DEBUG

    DEBUG = DEBUG
except:
    DEBUG = False

ALLOWED_HOSTS = ["*"]

CORS_ORIGIN_WHITELIST = (
    'localhost:8000',
)

AUTH_USER_MODEL = "genetica_auth.User"

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'genetica.auth',
    'genetica.reports',
    'genetica.services',
    'genetica.specimens',
    'genetica.user_profiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'RS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': VERIFY_KEY,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(days=365),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=365),
}

ROOT_URLCONF = 'genetica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'genetica.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

try:
    from .local_settings import DATABASES

    DATABASES = DATABASES
except:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'genetica',
            'USER': 'postgres',
            'PASSWORD': 'Postgres1@#',
            'HOST': 'localhost',
            'PORT': '5432'
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
