# Generated by Django 3.0.4 on 2020-03-28 15:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('prepare', 'Preparing'), ('ready', 'Ready')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='traittemplate',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
